fix: csv dataobject import reload column configuration
Error: CSV DataObject import, tab panel "CSV Settings", button "Reload column configuration" triggered error "Uncaught TypeError: this.callback is undefined" in updateColumnConfig
Caused by: Argument "showReload" was missing in constructor call
Introduced by: 6f813258e0ca0413ecc42fb1e7b66dd038d1584a
Relates to: Issue #6462